### ISSUE TITLE
Barcode scanner is not working

### ISSUE THREAD

**Issue by mamidipalli** [GoogleCloudPlatform/iot-smart-home-cloud#1]
QR Code with TEXT, to register a new device is not being scanned.
```_detector.detectInImage(firebaseImage)``` is not returning any Barcode objects.

**Comment by devunwired** [comment]
Hi Ravi, can you provide some more details about the device you are using to run the sample code?

You might also try playing around with the resolution settings inside of [register.dart](https://github.com/GoogleCloudPlatform/iot-smart-home-cloud/blob/master/mobile/lib/register.dart#L126). The sample uses `ResolutionPreset.low` for the best frame rate, but on your device you might get better results with a higher value.

Finally, you could verify whether or not the [official ML Kit Vision Flutter sample](https://github.com/flutter/plugins/tree/master/packages/firebase_ml_vision) detects properly on your device. If not, you may consider filing an issue with the plugin support for your device.

**Comment by mamidipalli** [comment]
Hi Dave, Thanks for the response.

I am using `One Plus 5` device for testing. I have changed the resolution settings to ```ResolutionPreset.high``` and it is working now.

**Comment by mamidipalli** [comment]
The issue is resolved.
