### ISSUE TITLE
404 Page not found - https://smarthome-xxxxxx.firebaseapp.com/login

### ISSUE THREAD

**Issue by sw-dev-code** [GoogleCloudPlatform/iot-smart-home-cloud#10]
When I finish **gmail** login at **Device Manager Web** following error occur:
`
404 Page Not Found : https://smarthome-xxxxxx.firebaseapp.com/login`

Why does this page missing?

**Comment by devunwired** [comment]
I believe this usually happens when the `authDomain` parameter in your Firebase config is set incorrectly and/or doesn't match the URL where you have the project hosted.

**Comment by sw-dev-code** [comment]
`authDomain` is set to `smarthome-xxxxxx.firebaseapp.com`
From picture below you can see that the URL is the same as the one where project is hosted.

![image](https://user-images.githubusercontent.com/13959599/78146366-5dda5d00-7432-11ea-90b2-c04e472e2292.png)

**Comment by sw-dev-code** [comment]
@devunwired This issue is solved for now. But I don't see my device in `https://smarthome-xxxxxx.firebaseapp.com/devices`. Do I have to build and use mobile app or I can add device on some other way?

**Comment by devunwired** [comment]
Devices are provisioned using the mobile app. The same way that a user would provision a device when they power it up. The web interface only manages existing provisioned devices.

**Comment by sw-dev-code** [comment]
@devunwired Can you tell me or give me instruction how to provision device without mobile app, please? My `devices` page is blank even if IoT Core is communicating with sample device.

**Comment by devunwired** [comment]
For now, you may find this [Medium blog post](https://medium.com/google-developers/building-a-smart-home-cloud-service-with-google-1ee436ac5a03) helpful. This sample is a companion to that post series.

**Comment by sw-dev-code** [comment]
I've followed that blog post, but I'm unable to build the Android app (issue: https://github.com/GoogleCloudPlatform/iot-smart-home-cloud/issues/11). So now I'm unable to add the device, and there is no action on Google Home app.

**Comment by mamidipalli** [comment]
You can provision a device by adding a document into the ‘pending’
collection in Firestore.


Create a collection with name ‘pending’ and create a document in it with
below fields and values. You should have the corresponding device created
in IoT core and the ‘registerDevice’ cloud function deployed before you do
this.


type: <type of the device>

serial_number: <the name you want to give to the device>

public_key: <the public key of the device without PEM formatting>

owner: <the Firebase UID of the user>


Below is an example to add a light device:


type : *light*

serial_number : *Kitchen Light*

public_key :
*MFkwEwYHKoZIzj9CAQYIKoZIzj0DAPcDQgAEzCL9v0EoI/KqNjPIivaFlrG8RIlr/wyNdCKJFUJAD8Qt0AHhkRSmwZR1477r7aPb1Pi/cty8irwDcTBo3D+biw==*

owner : *g9luW87m33c9f8CIIRhKAb7lSqW2*
