### ISSUE TITLE
Test device isn't showing in Smart Home Google app after account linking.

### ISSUE THREAD

**Issue by sw-dev-code** [GoogleCloudPlatform/iot-smart-home-cloud#12]

**Comment by sw-dev-code** [comment]
Any help on this?

**Comment by devunwired** [comment]
Based on the other issues you've filed, it's unclear where you are in the process and the exact problem you are having:
1. Have you built and provisioned a device using the mobile app?
1. Can you see that device in the web frontend?
1. If so, are there any [errors shown](https://developers.google.com/assistant/smarthome/develop/error-logging) in your cloud project that may help point to the issue?

**Comment by sw-dev-code** [comment]
@devunwired I don't know how to deploy mobile app when I finish with coping of google-services.json file

**Comment by proppy** [comment]
Closing as obsolete.
