### ISSUE TITLE
AAPT: error: resource android:attr/fontVariationSettings not found.

### ISSUE THREAD

**Issue by chakshujain** [GoogleCloudPlatform/iot-smart-home-cloud#13]
Hello @devunwired  , I've successfully followed the flutter-mobile part till setting up Firebase google-services.json and GoogleService-Info.plist files in  their respective directories. But still i got stuck here with this error.. 

/home/ck/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/9e33028a37e6b11fe4991f1b7c19ebd6/res/values/values.xml: AAPT: error: resource android:attr/fontVariationSettings not found.

/home/ck/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/9e33028a37e6b11fe4991f1b7c19ebd6/res/values/values.xml: AAPT: error: resource android:attr/ttcIndex not found.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.

**Comment by ManuverGujjar** [comment]
i just fixed that error you can check in 'pull request' tab

**Comment by devunwired** [comment]
Fixed with https://github.com/GoogleCloudPlatform/iot-smart-home-cloud/pull/15
